/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	// tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

	// But you can create a sidebar manually
	// /*
	mainSidebar: [
		'quickstart',
		'receivingMessages',
		'projectSetup',
		{
			type: 'category',
			label: 'API reference',
			items: [
				{
					type: 'category',
					label: 'WhatsApp',
					items: [
						'api-reference/whatsapp/this',
						`api-reference/whatsapp/version`,
						`api-reference/whatsapp/updateTimeout`,
						`api-reference/whatsapp/updateSenderNumberId`,
						`api-reference/whatsapp/updateAccessToken`,
					],
				},
				{
					type: 'category',
					label: 'Messages',
					items: [
						'api-reference/messages/this',
						`api-reference/messages/audio`,
						`api-reference/messages/contacts`,
						`api-reference/messages/document`,
						`api-reference/messages/image`,
						`api-reference/messages/interactive`,
						`api-reference/messages/location`,
						`api-reference/messages/status`,
						`api-reference/messages/sticker`,
						`api-reference/messages/template`,
						`api-reference/messages/text`,
						`api-reference/messages/video`,
					],
				},
				{
					type: 'category',
					label: 'Phone numbers',
					items: [
						'api-reference/phoneNumbers/this',
						`api-reference/phoneNumbers/requestCode`,
						`api-reference/phoneNumbers/verifyCode`,
					],
				},
				{
					type: 'category',
					label: 'Two-step verification',
					items: [
						'api-reference/twoStepVerification/this',
						`api-reference/twoStepVerification/setPin`,
					],
				},
				{
					type: 'category',
					label: 'Webhooks',
					items: [
						'api-reference/webhooks/this',
						'api-reference/webhooks/isStarted',
						'api-reference/webhooks/start',
						'api-reference/webhooks/stop',
					],
				},
				{
					type: 'category',
					label: 'Types',
					items: [
						'api-reference/types/ActionObject',
						'api-reference/types/AudioMediaObject',
						'api-reference/types/addresses_object',
						'api-reference/types/button_parameter_object',
						'api-reference/types/component_object',
						'api-reference/types/ContactObject',
						'api-reference/types/currency_object',
						'api-reference/types/date_time_object',
						'api-reference/types/DocumentMediaObject',
						'api-reference/types/EmailObject',
						'api-reference/types/HeaderObject',
						'api-reference/types/ImageMediaObject',
						'api-reference/types/InteractiveObject',
						'api-reference/types/language_object',
						'api-reference/types/LocationObject',
						'api-reference/types/NameObject',
						'api-reference/types/OrgObject',
						'api-reference/types/PhoneObject',
						'api-reference/types/ProductObject',
						'api-reference/types/ReplyButtonObject',
						'api-reference/types/RequestCodeObject',
						'api-reference/types/RowObject',
						'api-reference/types/SectionObject',
						'api-reference/types/SetPinResponseObject',
						'api-reference/types/SimpleTextObject',
						'api-reference/types/StatusObject',
						'api-reference/types/StickerMediaObject',
						'api-reference/types/TemplateObject',
						'api-reference/types/TextObject',
						'api-reference/types/URLObject',
						'api-reference/types/VerifyCodeObject',
						'api-reference/types/VideoMediaObject',
						'api-reference/types/WAConfigType',
						'api-reference/types/webhookCallbackFunction',
					],
				},
			],
		},
	],
	//  */
};

module.exports = sidebars;
