/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  // /*
  mainSidebar: [
    'quickstart',
    'receiving_messages',
    'project_setup',
    {
      type: 'category',
      label: 'API reference',
      items:
      [
        {
          type: 'category',
          label: 'WhatsApp',
          items:
          [
            'api-reference/whatsapp/this',
            `api-reference/whatsapp/version`,
            `api-reference/whatsapp/update_timeout`,
            `api-reference/whatsapp/update_sender_number_id`,
            `api-reference/whatsapp/update_access_token`,
          ]
        },
        {
          type: 'category',
          label: 'Messages',
          items:
          [
            'api-reference/messages/this',
            `api-reference/messages/audio`,
            `api-reference/messages/contacts`,
            `api-reference/messages/document`,
            `api-reference/messages/image`,
            `api-reference/messages/interactive`,
            `api-reference/messages/location`,
            `api-reference/messages/status`,
            `api-reference/messages/sticker`,
            `api-reference/messages/template`,
            `api-reference/messages/text`,
            `api-reference/messages/video`,
          ]
        },
        {
          type: 'category',
          label: 'Webhooks',
          items:
          [
            'api-reference/webhooks/this',
            'api-reference/webhooks/is_started',
            'api-reference/webhooks/start',
            'api-reference/webhooks/stop'
          ]
        },
        {
          type: 'category',
          label: 'Types',
          items:
          [
            'api-reference/types/action_object',
            'api-reference/types/audio_media_object',
            'api-reference/types/addresses_object',
            'api-reference/types/button_parameter_object',
            'api-reference/types/component_object',
            'api-reference/types/contact_object',
            'api-reference/types/currency_object',
            'api-reference/types/date_time_object',
            'api-reference/types/document_media_object',
            'api-reference/types/email_object',
            'api-reference/types/header_object',
            'api-reference/types/image_media_object',
            'api-reference/types/interactive_object',
            'api-reference/types/language_object',
            'api-reference/types/location_object',
            'api-reference/types/name_object',
            'api-reference/types/org_object',
            'api-reference/types/phone_object',
            'api-reference/types/product_object',
            'api-reference/types/reply_buttons_object',
            'api-reference/types/row_object',
            'api-reference/types/section_object',
            'api-reference/types/simple_text_object',
            'api-reference/types/status_object',
            'api-reference/types/sticker_media_object',
            'api-reference/types/template_object',
            'api-reference/types/text_object',
            'api-reference/types/url_object',
            'api-reference/types/video_media_object',
            'api-reference/types/wa_config_type',
          ]
        }
      ],
    },
  ],
  //  */
};

module.exports = sidebars;
